[project]
name = "topographic-system-kart"
version = "0.1.0"
description = "A collection of tools to deal with kart for LINZ Topographic Data"
requires-python = ">=3.12"
dependencies = [
    "linz-logger",
]
[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "ruff",
]
