[project]
name = "topographic-system-kart"
version = "0.1.1"
description = "A collection of tools to deal with kart for LINZ Topographic Data"
requires-python = ">=3.12"
dependencies = [
    "linz-logger",
    # "kart" executable must be available. See kartproject.org for installation instructions.
]
[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "ruff",
]
