[project]
name = "topographic-system-kart"
version = "0.1.0"
description = "A collection of tools to deal with kart for LINZ Topographic Data"
requires-python = ">=3.12"
dependencies = [
    "linz-logger",
]
[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "ruff",
]

[tool.mypy]
show_error_codes = true
strict = true
disable_error_code = ["import"]
[[tool.mypy.overrides]]
module = ["qgis.core"]
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = ["linz_logger"]
ignore_missing_imports = true
